title: GESS Mobile App Technical Docs
author: L.M.Dissanayake
remote_theme: just-the-docs/just-the-docs

# Navigation Settings
nav_config:
  look_n_feel: default

# Search allows others to find specific code blocks easily
search_enabled: true